services:
  client:
    build:
      context: ./client
    ports:
      - "5080:80"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
    ports:
      - "5081:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI:-mongodb://mongo:27017/todo-app}
      - PORT=5000
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local 